# Generated by Django 2.2.1 on 2019-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=32)),
                ('degree', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('company', models.CharField(max_length=64)),
                ('business_unit', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('start_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(max_length=8)),
                ('summary', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
                ('summary', models.CharField(max_length=32)),
            ],
        ),
    ]
