# Generated by Django 2.2.1 on 2019-06-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
